### ISSUE TITLE
not able to withdraw 

### ISSUE THREAD

**Issue by duplixx** [PatrickAlphaC/html-fund-me-fcc#10]
https://user-images.githubusercontent.com/90516956/184483266-1e7b7171-dcac-4ec6-8a17-c3f54ff6952a.mp4

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be

**Comment by wuzhenbin** [comment]
I meet same situation , at last i checked contract url and found it is incorrect.
