### ISSUE TITLE
js issues helpz

### ISSUE THREAD

**Issue by wangyangv1** [PatrickAlphaC/html-fund-me-fcc#12]
when we  test the fund function in index.js 

i checked my code there is no differenet with example code 

but my chrome gave me this error plz help

![image](https://user-images.githubusercontent.com/49341812/187491124-97fc2c5c-3979-40e8-ae85-7f5995a41e05.png)
<img width="792" alt="image" src="https://user-images.githubusercontent.com/49341812/187491141-c4f8ca00-e58b-43f3-a4fe-50e006908b8f.png">

**Comment by ippy1997** [comment]
can you post the full JS code and please try to report problems like this in the discussions fourm of the course on github which you can find here :  https://github.com/smartcontractkit/full-blockchain-solidity-course-js/discussions

**Comment by PatrickAlphaC** [comment]
your `contractAddress` is likely not an address. Try `console.log(contractAddress)` to see what it is.
