### ISSUE TITLE
metamask not connecting to local network 

### ISSUE THREAD

**Issue by myselfunknown00** [PatrickAlphaC/html-fund-me-fcc#16]
Hello Sir! @PatrickAlphaC  and everyone I have an issue Kindly help me !

when I try to add a new network in metamask and add my RPC URL and ChainId it gives an error 

`Could not fetch chain ID. Is your RPC URL correct?`

![Screenshot 2022-10-02 52154165](https://user-images.githubusercontent.com/83874564/193429107-22972847-04bd-46dc-9504-e019819833b0.png)

and when I try to save it shows 

![Screenshot 2022-10-02 023512](https://user-images.githubusercontent.com/83874564/193429230-4ebd0ba2-dd06-4d81-8798-d526e5f20476.png)

my hardhat localhost is running in the background 

![dksfjal](https://user-images.githubusercontent.com/83874564/193429278-5fa80164-6db1-40cb-913c-e78cabc81196.png)

what should i do I'm stuck...

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
