### ISSUE TITLE
window.ethereum "undefined"

### ISSUE THREAD

**Issue by mohammedalasly** [PatrickAlphaC/html-fund-me-fcc#23]
Hi everybody! :wave:
I just started with **lesson 8: HTML / Javascript Fund Me (Full Stack / Front End)** 
At the beginning of the lesson, i tried to check  `window.ethereum`  on the Chrome browser console and it showed me  `undefined`  :confused: although i have `MetaMask` installed and i was using it along with the course with no problems. 
I'll keep following along with coding tho, and if any of you can help me with this, i'd really appreciate it.

**Comment by PatrickAlphaC** [comment]
Hello!

Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
