### ISSUE TITLE
Error: Transaction reverted: function selector was not recognized and there's no fallback function (BUT contract calls still work?!)

### ISSUE THREAD

**Issue by eugenekhoo1** [PatrickAlphaC/html-fund-me-fcc#27]
Hi! I keep getting the following error when i call the fund contract. And it also seems that when i call it once, it runs multiple times in my hardhat node (with the same errors coming out several times)

```
eth_call
  Contract call:       FundMe#<unrecognized-selector>
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0xe7f1725e7734ce288f8367e1bb143e90bb3f0512

  Error: Transaction reverted: function selector was not recognized and there's no fallback function
```

But when i check the console in my webpage, it seems to have worked (and i also got the transaction confirmations in metamask)

![Screenshot 2023-06-07 at 1 08 27 PM](https://github.com/PatrickAlphaC/html-fund-me-fcc/assets/115082788/283af7b4-948b-4c10-b309-c9eeb7bc7fff)

Is this normal? even though the contract calls are working properly with getBalance and withdraw

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be

**Comment by PatrickAlphaC** [comment]
Sorry, this is a known bug with hardhat and Metamask.

It's all good, you can ignore the error.
