### ISSUE TITLE
Error, when i use withdraw function

### ISSUE THREAD

**Issue by egemenkus** [PatrickAlphaC/html-fund-me-fcc#9]
![image](https://user-images.githubusercontent.com/47275560/183988415-35331968-f4c1-4416-8f58-9398833d2067.png)

**When i try withdraw function i am getting the above error but other functions works very well. Can you help me?**

**Comment by pedromota12** [comment]
i ran into the same problem, it seems using other accounts than the account #0 that is generated when you run the command (yarn hardhat node) makes the MetaMask not detecting the account as the owner but as the FundMe_NotOwner. I hope this is the case and it helps with your code.

**Comment by egemenkus** [comment]
> 

Thank you so much. It works.

**Comment by eugenekhoo1** [comment]
is there a way to retrieve the list of accounts once i have run hardhat node? i did not import the 0th account..
